
name: Build Debian Packages (Legacy)
on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:
  
  pull_request:
    branches:
      - legacy-1.0.x
    paths:
      - 'debian/changelog'

jobs:
  build:
    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }}
    runs-on: 'ubuntu-22.04'

    strategy:
      matrix:
        distro: [buster,bullseye]
        arch: [armhf]
    

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Debian package
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-webui_package
          path: ${{ steps.build-debian-package.outputs.deb-package }}
