
name: Deploy to Gemfury (Legacy)
on:
  push:
    branches:
      - legacy-1.0.x
    paths:
      - 'debian/changelog'

jobs:
  build:
    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }}

    runs-on: 'ubuntu-20.04'

    strategy:
      matrix:
        distro: [buster]
        arch: [armhf]
  
    environment: GEMFURY

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Debian package
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-webui_package
          path: ${{ steps.build-debian-package.outputs.deb-package }}

      - name: Upload Package to Gemfury
        uses: danielmundi/upload-gemfury@main
        with:
          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
          gemfury-username: ${{ secrets.GEMFURY_NAME }}
          gemfury-token: ${{ secrets.GEMFURY_TOKEN }}

  
  slack-workflow-status:
    if: always()
    name: Post Workflow Status to Slack
    needs:
      - sbuild
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}