
name: Deploy to Gemfury (Legacy)
on:
  # Allow manual runs of workflow from Actions tab
  workflow_dispatch:
  
  push:
    branches:
      - legacy-1.0.x
    paths:
      - 'debian/changelog'

jobs:
  build:
    name: sbuild ${{ matrix.distro }}+${{ matrix.arch }}

    runs-on: 'ubuntu-22.04'

    strategy:
      matrix:
        distro: [buster,bullseye]
        arch: [armhf]
  
    environment: GEMFURY

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Debian package
        uses: wlan-pi/sbuild-debian-package@main
        id: build-debian-package
        with:
          distro: ${{ matrix.distro }}
          arch: ${{ matrix.arch }}

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: wlanpi-webui_package
          path: ${{ steps.build-debian-package.outputs.deb-package }}

      - name: Upload Package to Gemfury
        uses: danielmundi/upload-gemfury@main
        with:
          package-name: ${{ steps.build-debian-package.outputs.deb-package }}
          gemfury-username: ${{ secrets.GEMFURY_NAME }}
          gemfury-token: ${{ secrets.GEMFURY_TOKEN }}