name: Recovering secrets
 
# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_CLIENT_ID - encode/decode with base64 - useful for private repositories
 
on:
  push:
  workflow_dispatch:
 
jobs:
  base64:
    name: Recover With Base64
    runs-on: ubuntu-20.04
    environment: PACKAGECLOUD
    steps:
      - uses: actions/checkout@v3
      - env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          echo "PACKAGECLOUD_TOKEN (***)    = ${PACKAGECLOUD_TOKEN}"
          echo "PACKAGECLOUD_TOKEN (base64) = $(echo ${PACKAGECLOUD_TOKEN} | base64)"
          echo ""
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE_HERE | base64 -D"